Repository bazelbuild/bazel-toolchains, pull requests merged in 2019-10, with the labels that each got.

#711 Add rbe_exec_properties and custom_exec_properties
  .bazelci/presubmit.yml
  WORKSPACE
  rules/experimental/rbe/exec_properties.bzl
  tests/rules/experimental/rbe/BUILD
Labels: approved, cla: yes, lgtm, size/L

#717 add test that runs with rbe Ubuntu 18.04
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
  tests/rbe_repo/rbe_ubuntu_1804.yaml
Labels: approved, cla: yes, lgtm, size/M

#718 Added docker_shm_size parameter to create_exec_properties_dict
  rules/experimental/rbe/exec_properties.bzl
Labels: approved, cla: yes, lgtm, size/S

#719 create toolchain for ubsan for containers that come with clang 10.0.0
  configs/experimental/ubuntu16_04_clang/1.3/bazel_0.29.1/ubsan/BUILD
  configs/experimental/ubuntu16_04_clang/1.3/bazel_0.29.1/ubsan/armeabi_cc_toolchain_config.bzl
  configs/experimental/ubuntu16_04_clang/1.3/bazel_0.29.1/ubsan/builtin_include_directory_paths
  configs/experimental/ubuntu16_04_clang/1.3/bazel_0.29.1/ubsan/cc_toolchain_config.bzl
  configs/experimental/ubuntu16_04_clang/1.3/bazel_0.29.1/ubsan/cc_wrapper.sh
  tests/rbe_external_project/abseil_ubsan.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#720 Add an exec_properties attr to rbe_autoconfig
  WORKSPACE
  rules/experimental/rbe/exec_properties.bzl
  rules/rbe_repo.bzl
  rules/rbe_repo/BUILD.platform.tpl
  rules/rbe_repo/build_gen.bzl
  tests/rules/experimental/rbe/BUILD
Labels: approved, cla: yes, lgtm, size/L

#721 use exec_properties in @buildkite_config
  .bazelci/presubmit.yml
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/S

#728 Remove jdk_version from create_exec_properties_dict.
  rules/experimental/rbe/exec_properties.bzl
Labels: approved, cla: yes, lgtm, size/XS

#738 updating container for tests
  WORKSPACE
  tests/rbe_repo/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#736 manually producing configs for bazel 1.0.0
  bazelrc/bazel-1.0.0.bazelrc
  bazelrc/latest.bazelrc
  configs/ubuntu16_04_clang/9.0.0/bazel_1.0.0/cc/BUILD
  configs/ubuntu16_04_clang/9.0.0/bazel_1.0.0/cc/armeabi_cc_toolchain_config.bzl
  configs/ubuntu16_04_clang/9.0.0/bazel_1.0.0/cc/builtin_include_directory_paths
  configs/ubuntu16_04_clang/9.0.0/bazel_1.0.0/cc/cc_toolchain_config.bzl
  configs/ubuntu16_04_clang/9.0.0/bazel_1.0.0/cc/cc_wrapper.sh
  configs/ubuntu16_04_clang/9.0.0/bazel_1.0.0/config/BUILD
  configs/ubuntu16_04_clang/9.0.0/bazel_1.0.0/java/BUILD
  configs/ubuntu16_04_clang/versions.bzl
Labels: approved, cla: yes, lgtm, release, size/XXL

#735 Rename argument names in rbe_exec_properties and custom_exec_properties.
  WORKSPACE
  rules/experimental/rbe/exec_properties.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#743 Move documentation to a README file.
  rules/experimental/rbe/README.md
  rules/experimental/rbe/exec_properties.bzl
Labels: approved, cla: yes, lgtm, size/L

#744 Experimental
  .bazelci/presubmit.yml
  WORKSPACE
  rules/exec_properties/BUILD
  rules/exec_properties/README.md
  rules/exec_properties/exec_properties.bzl
  rules/rbe_repo/build_gen.bzl
  tests/rules/exec_properties/BUILD
  tests/rules/exec_properties/network_disabled.sh
  tests/rules/exec_properties/network_enabled.sh
  tests/rules/exec_properties/privileged_off.sh
  tests/rules/exec_properties/privileged_on.sh
Labels: approved, cla: yes, lgtm, size/S

#751 creating manually configs for Bazel 1.0.1
  WORKSPACE
  configs/ubuntu16_04_clang/10.0.0/bazel_1.0.1/cc/BUILD
  configs/ubuntu16_04_clang/10.0.0/bazel_1.0.1/cc/armeabi_cc_toolchain_config.bzl
  configs/ubuntu16_04_clang/10.0.0/bazel_1.0.1/cc/builtin_include_directory_paths
  configs/ubuntu16_04_clang/10.0.0/bazel_1.0.1/cc/cc_toolchain_config.bzl
  configs/ubuntu16_04_clang/10.0.0/bazel_1.0.1/cc/cc_wrapper.sh
  configs/ubuntu16_04_clang/10.0.0/bazel_1.0.1/config/BUILD
  configs/ubuntu16_04_clang/10.0.0/bazel_1.0.1/java/BUILD
  configs/ubuntu16_04_clang/versions.bzl
  tests/rbe_repo/BUILD
Labels: approved, cla: yes, lgtm, size/XXL

#752 Fix broken links and fix docs.
  rules/exec_properties/README.md
  rules/exec_properties/exec_properties.bzl
Labels: approved, cla: yes, lgtm, size/S

#754 creating ubsan configs for Bazel 1.0.0
  configs/experimental/ubuntu16_04_clang/1.3/bazel_1.0.0/ubsan/BUILD
  configs/experimental/ubuntu16_04_clang/1.3/bazel_1.0.0/ubsan/armeabi_cc_toolchain_config.bzl
  configs/experimental/ubuntu16_04_clang/1.3/bazel_1.0.0/ubsan/builtin_include_directory_paths
  configs/experimental/ubuntu16_04_clang/1.3/bazel_1.0.0/ubsan/cc_toolchain_config.bzl
  configs/experimental/ubuntu16_04_clang/1.3/bazel_1.0.0/ubsan/cc_wrapper.sh
  tests/rbe_external_project/abseil_ubsan.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#748 Add labels parameter to create_exec_properties_dict.
  rules/exec_properties/exec_properties.bzl
  tests/rules/exec_properties/BUILD
  tests/rules/exec_properties/compare.bzl
Labels: approved, cla: yes, lgtm, size/L

#755 Add documentation for using exec_properties in rbe_autoconfig
  rules/rbe_repo.bzl
Labels: approved, cla: yes, lgtm, size/M
