Repository bazelbuild/bazel-toolchains, pull requests merged in 2019-09, with the labels that each got.

#691 explicitly list out env var in every step of cloudbuild
  tests/rbe_repo/generate_confs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#685 Rename the docker_network_enabled param to docker_enabled.
  rules/experimental/rbe/exec_properties.bzl
  tests/rules/experimental/rbe/BUILD
Labels: approved, cla: yes, do-not-merge/hold, size/M

#695 extend timeout for generate confs test
  tests/rbe_repo/generate_confs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#694 Update rules README
  rules/README.md
Labels: approved, cla: yes, lgtm, size/S

#701 Remove package metadata rules that moved to rules_docker
  BUILD
  WORKSPACE
  deps/io_bazel_rules_go.bzl
  repositories/go_repositories.bzl
  repositories/repositories.bzl
  rules/container/BUILD
  rules/container/metadata_merge.bzl
  rules/container/packages_metadata.bzl
  src/go/cmd/metadata_merge/BUILD
  src/go/cmd/metadata_merge/metadata_merge.go
  src/go/cmd/packages_metadata/BUILD
  src/go/cmd/packages_metadata/packages_metadata.go
  src/go/pkg/metadata/BUILD
  src/go/pkg/metadata/packages.go
  tests/rules/BUILD
  tests/rules/metadata_merge_file1.yaml
  tests/rules/metadata_merge_file2.yaml
  tests/rules/metadata_merge_file3.yaml
  tests/rules/metadata_merge_file4.yaml
  tests/rules/packages_metadata.csv
Labels: approved, cla: yes, lgtm, size/XL

#710 Add rbe_autoconfig target for RBE ubuntu1804 image integration test
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/S

#712 add warning if current running bazel is ahead of bazel-toolchains repo
  rules/rbe_repo/checked_in.bzl
  rules/rbe_repo/version_check.bzl
Labels: approved, cla: yes, lgtm, size/S
