Repository bazelbuild/bazel-toolchains, pull requests merged in 2019-11, with the labels that each got.

#760 Toolchain configs for for marketplace.gcr.io/google/rbe-ubuntu16-04, Bazel 1.1.0 (2019/11/05)
  configs/dependency-tracking/ubuntu1604.bzl
  configs/ubuntu16_04_clang/10.0.0/bazel_1.1.0/config/BUILD
  configs/ubuntu16_04_clang/versions.bzl
  tests/rbe_external_project/bazel.yaml
  tests/rbe_external_project/bazel_jdk11.yaml
Labels: approved, cla: yes, lgtm, release, size/S

#758 Remove recommendation to use create_exec_properties_dict only in WORKSPACE
  rules/exec_properties/README.md
Labels: approved, cla: yes, do-not-merge/hold, size/XS

#763 Replace create_exec_properties_dict with create_rbe_exec_properties_dict
  .gitignore
  WORKSPACE
  rules/exec_properties/README.md
  rules/exec_properties/exec_properties.bzl
  rules/rbe_repo.bzl
  rules/rbe_repo/build_gen.bzl
  tests/rules/exec_properties/BUILD
  tests/rules/exec_properties/compare.bzl
Labels: approved, cla: yes, lgtm, size/L

#769 fix abseil ubsan tests
  tests/rbe_external_project/abseil_ubsan.yaml
Labels: approved, cla: yes, lgtm, size/XS

#771 Move tests that use 'docker' to GCB
  .bazelci/presubmit.yml
  configs/ubuntu16_04_clang/docker_toolchain_autoconfig_tests.yaml
  tests/config/.bazelrc
  tests/config/docker_toolchain_autoconfig_tests.yaml
Labels: approved, cla: yes, lgtm, size/L
