Repository bazelbuild/bazel-toolchains, pull requests merged in 2019-05, with the labels that each got.

#514 Delete configs release history as the tagging scheme is being changed
  configs/ubuntu16_04_clang/releases.yaml
Labels: lgtm, size/L

#521 Add OWNERs file for prow/tide
  OWNERS
Labels: lgtm, size/S

#524 refactor rbe_repo rule in preparation to add new features
  WORKSPACE
  rules/rbe_repo.bzl
  rules/rbe_repo/.latest.bazelrc.tpl
  rules/rbe_repo/BUILD
  rules/rbe_repo/BUILD.cc_alias.tpl
  rules/rbe_repo/BUILD.java.tpl
  rules/rbe_repo/BUILD.java_alias.tpl
  rules/rbe_repo/BUILD.platform.tpl
  rules/rbe_repo/build_gen.bzl
  rules/rbe_repo/checked_in.bzl
  rules/rbe_repo/container.bzl
  rules/rbe_repo/extract.sh.tpl
  rules/rbe_repo/get_java_home.sh.tpl
  rules/rbe_repo/outputs.bzl
  rules/rbe_repo/util.bzl
  rules/rbe_repo/version_check.bzl
Labels: approved, lgtm, size/XXL

#530 adding basic external repo example
  cloudbuild.yaml
  tests/rbe_repo/examples/bazel_toolchains_client/BUILD
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
  tests/rbe_repo/examples/bazel_toolchains_client/hello_world.cc
  tests/rbe_repo/examples/bazel_toolchains_client/say_hello.cc
  tests/rbe_repo/examples/bazel_toolchains_client/say_hello.h
  tests/rbe_repo/examples/bazel_toolchains_client/say_hello_test.cc
Labels: approved, lgtm, size/L

#533 make bazel_test_cloudbuild.yaml more generic
  bazel_tests_cloudbuild.yaml
  tests/rbe_repo/bazel_legacy_configs.yaml
Labels: approved, lgtm, size/M

#536 Adding a bazelrc for Bazel 0.26
  bazelrc/bazel-0.26.0.bazelrc
  bazelrc/latest.bazelrc
Labels: approved, lgtm, size/M

#535 Create rbe_repo definitions and validations
  configs/ubuntu16_04_clang/versions_to_migrate.bzl
  rules/rbe_repo.bzl
  rules/rbe_repo/toolchain_config_suite_spec.bzl
  tests/rbe_repo/BUILD
Labels: approved, lgtm, size/XL

#538 cleanups split off from large PR
  .bazelignore
  WORKSPACE
  rules/BUILD
  rules/container/BUILD
  rules/rbe_repo/BUILD
  rules/rbe_repo/container.bzl
  rules/rbe_repo/version_check.bzl
  tests/rbe_repo/BUILD
Labels: approved, lgtm, size/M

#539 fix output_base test
  .gitignore
  WORKSPACE
  tests/rbe_repo/BUILD
  tests/rbe_repo/output_base.yaml
Labels: approved, lgtm, size/S

#540 use incompatible py toolchains flags by default
  .bazelci/presubmit.yml
  .bazelrc
Labels: approved, lgtm, size/S

#541 add OSFamily Linux to generated platforms
  rules/rbe_repo/BUILD.platform.tpl
  tests/rbe_repo/BUILD
Labels: approved, lgtm, size/M
