Repository bazelbuild/bazel-toolchains, pull requests merged in 2019-07, with the labels that each got.

#611 Fix bad Starlark string escapes
  rules/rbe_repo/container.bzl
  rules/rbe_repo/util.bzl
Labels: approved, lgtm, size/XS

#617 update rules_docker + add call to go_deps
  WORKSPACE
  deps/io_bazel_rules_docker.bzl
Labels: approved, lgtm, size/XS

#619 Removing dependency on base images docker package managers
  .bazelci/presubmit.yml
  .bazelrc
  WORKSPACE
  deps/base_images_docker.bzl
  deps/io_bazel_rules_docker.bzl
  repositories/repositories.bzl
  rules/container/debian_pkg_tar.bzl
  rules/container/docker_toolchains.bzl
  rules/docker_config.bzl
  src/go/cmd/packages_metadata/packages_metadata.go
Labels: approved, lgtm, size/M

#623 remove test that times out
  tests/rbe_external_project/abseil_tsan.yaml
Labels: approved, lgtm, size/XS

#624 Add bazelrc file for 0.28
  bazelrc/bazel-0.28.0.bazelrc
  bazelrc/latest.bazelrc
Labels: approved, lgtm, size/M

#627 Update CODEOWNERS
  CODEOWNERS
Labels: approved, lgtm, size/XS

#626 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#629 remove toolchain container rules
  .bazelci/presubmit.yml
  rules/container/BUILD
  rules/container/debian_pkg_tar.bzl
  rules/container/docker_toolchains.bzl
  tests/config/BUILD
  tests/container/BUILD
  tests/container/tests.yaml
Labels: approved, lgtm, size/XL

#634 Create ubsan toolchain config for 0.28.0
  configs/experimental/ubuntu16_04_clang/1.2/bazel_0.28.0/ubsan/BUILD
  configs/experimental/ubuntu16_04_clang/1.2/bazel_0.28.0/ubsan/armeabi_cc_toolchain_config.bzl
  configs/experimental/ubuntu16_04_clang/1.2/bazel_0.28.0/ubsan/cc_toolchain_config.bzl
  configs/experimental/ubuntu16_04_clang/1.2/bazel_0.28.0/ubsan/cc_wrapper.sh
  tests/rbe_external_project/abseil_ubsan.yaml
Labels: approved, lgtm, size/XXL

#636 fix use of run in docker_config and update rules_docker
  deps/io_bazel_rules_docker.bzl
  rules/docker_config.bzl
Labels: approved, lgtm, size/S

#639 Add test that validates all containers are pullable
  configs/ubuntu16_04_clang/versions.bzl
  rules/rbe_repo/outputs.bzl
  rules/rbe_repo/toolchain_config_suite_spec.bzl
  tests/config/no_updates/versions.bzl
  tests/config/trigger_config_gen/versions.bzl
  tests/rbe_repo/BUILD
  tests/rbe_repo/blank_versions_test.bzl
  tests/rbe_repo/examples/toolchain_config_host/configs/test_configs/versions.bzl
  tests/rbe_repo/rbe_container_test.sh
  tests/rbe_repo/versions.bzl
  tests/rbe_repo/versions_test.bzl
Labels: approved, lgtm, size/M

#644 rbe_autoconfig to select requested config
  rules/rbe_repo/checked_in.bzl
Labels: approved, do-not-merge/hold, lgtm, size/XS
