Repository bazelbuild/bazel-toolchains, pull requests merged in 2019-08, with the labels that each got.

#650 enable use of checked in configs with no java home set
  rules/rbe_repo.bzl
  rules/rbe_repo/toolchain_config_suite_spec.bzl
  tests/rbe_external_project/abseil.yaml
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
  tests/rbe_repo/examples/rbe_custom_no_java.yaml
  tests/rbe_repo/examples/toolchain_config_host/WORKSPACE
  tests/rbe_repo/examples/toolchain_config_host/configs/test_configs_no_java/BUILD
  tests/rbe_repo/examples/toolchain_config_host/configs/test_configs_no_java/repo.bzl
  tests/rbe_repo/examples/toolchain_config_host/configs/test_configs_no_java/versions.bzl
Labels: approved, lgtm, size/L

#654 fix external tests for bazel
  tests/rbe_external_project/add_rbe_default.sh
Labels: approved, lgtm, size/XS

#655 document better shell script to add content to WORKSPACE
  tests/rbe_external_project/add_rbe_default.sh
Labels: approved, lgtm, size/XS

#660 less debug info + fix issue with no java case
  rules/rbe_repo/checked_in.bzl
  rules/rbe_repo/toolchain_config_suite_spec.bzl
Labels: approved, lgtm, size/XS

#664 Add rules/exec_properties.bzl
  rules/experimental/rbe/BUILD
  rules/experimental/rbe/exec_properties.bzl
Labels: approved, lgtm, size/L

#669 Add create_exec_properties_dict tests
  tests/rules/experimental/rbe/BUILD
  tests/rules/experimental/rbe/network_disabled.sh
  tests/rules/experimental/rbe/network_enabled.sh
  tests/rules/experimental/rbe/privileged_off.sh
  tests/rules/experimental/rbe/privileged_on.sh
Labels: approved, lgtm, size/L

#671 Adding a rbe_exec_properties task to presubmit.yml
  .bazelci/presubmit.yml
Labels: approved, lgtm, size/S

#679 Make the rbe_exec_properties tests run on the current bazel version.
  .bazelci/presubmit.yml
Labels: approved, cla: yes, lgtm, size/XS

#668 Adding a bazelrc for 0.29
  bazelrc/bazel-0.29.0.bazelrc
  bazelrc/latest.bazelrc
Labels: approved, cla: yes, lgtm, size/M
