Repository bazelbuild/bazel-toolchains, pull requests merged in 2019-06, with the labels that each got.

#544 Add the PR bot as owner
  CODEOWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#545 Add pip dependencies of base images docker
  WORKSPACE
  deps/base_images_docker.bzl
Labels: approved, lgtm, size/S

#549 add tests that run RBE builds with external projects
  bazelrc/bazel-0.27.0.bazelrc
  tests/rbe_external_project/abseil.yaml
  tests/rbe_external_project/add_rbe_default.sh
  tests/rbe_external_project/baselisk.sh
  tests/rbe_external_project/bazel.yaml
  tests/rbe_external_project/bazel_baselisk_rc.yaml
Labels: approved, lgtm, size/L

#554 update versions.bzl now that internal process is updated
  configs/ubuntu16_04_clang/versions.bzl
  configs/ubuntu16_04_clang/versions_to_migrate.bzl
  rules/rbe_repo/toolchain_config_suite_spec.bzl
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
Labels: approved, lgtm, size/L

#556 Create a configs.tar file in rbe_autoconfig
  rules/rbe_repo.bzl
  rules/rbe_repo/outputs.bzl
  tests/rbe_repo/BUILD
  tests/rbe_repo/examples/bazel_toolchains_client/BUILD.config_tar_test
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
  tests/rbe_repo/examples/build_and_extract_configs_tar.sh
  tests/rbe_repo/examples/rbe_custom_config_tar.yaml
  tests/rbe_repo/examples/toolchain_config_host/WORKSPACE
  tests/rbe_repo/rbe_autoconf_checks.sh
Labels: approved, lgtm, size/L

#561 use external project for bazel legacy tests
  tests/rbe_repo/bazel_legacy_configs.yaml
  tests/rbe_repo/bazel_legacy_rbe_default.yaml
Labels: approved, lgtm, size/S

#563 Declare additonal metadata output for download_pkgs
  deps/base_images_docker.bzl
  rules/container/debian_pkg_tar.bzl
  rules/container/docker_toolchains.bzl
Labels: approved, lgtm, size/S

#564 change one more test to use external repo
  bazel_tests_cloudbuild.yaml
Labels: approved, lgtm, size/XS

#562 enabling generation of versions.bzl in rbe_autoconfig_autogen_ubuntu1604
  WORKSPACE
Labels: approved, lgtm, size/XS

#558 add test that uses jdk11
  WORKSPACE
  rules/rbe_repo.bzl
  rules/rbe_repo/build_gen.bzl
  rules/rbe_repo/checked_in.bzl
  rules/rbe_repo/container.bzl
  rules/rbe_repo/outputs.bzl
  rules/rbe_repo/toolchain_config_suite_spec.bzl
  tests/rbe_repo/BUILD
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
  tests/rbe_repo/examples/rbe_default_jdk11.yaml
Labels: approved, lgtm, size/L

#567 RBE tests that force generate configs
  bazel_tests_cloudbuild.yaml
  tests/rbe_external_project/bazel_bazelisk_rc.yaml
  tests/rbe_repo/bazel_legacy_rbe_default.yaml
  tests/rbe_repo/bazel_tests_generate_confs.yaml
  tests/rbe_repo/bazelisk.sh
  tests/rbe_repo/bazelrc/.bazelrc.0260.notoolchain
  tests/rbe_repo/bazelrc/.bazelrc.pre0260
  tests/rbe_repo/bazelrc/.bazelrc.pre0260.notoolchain
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
Labels: approved, lgtm, size/L

#566 Add new rule to transform package metadata for FUS
  BUILD
  WORKSPACE
  repositories/repositories.bzl
  rules/container/packages_metadata.bzl
  src/go/cmd/packages_metadata/BUILD
  src/go/cmd/packages_metadata/packages_metadata.go
  tests/rules/BUILD
  tests/rules/packages_metadata.csv
Labels: approved, lgtm, size/L

#574 add configs for 0.27.0
  WORKSPACE
  configs/dependency-tracking/ubuntu1604.bzl
  configs/ubuntu16_04_clang/9.0.0/bazel_0.27.0/cc/BUILD
  configs/ubuntu16_04_clang/9.0.0/bazel_0.27.0/cc/armeabi_cc_toolchain_config.bzl
  configs/ubuntu16_04_clang/9.0.0/bazel_0.27.0/cc/cc_toolchain_config.bzl
  configs/ubuntu16_04_clang/9.0.0/bazel_0.27.0/cc/cc_wrapper.sh
  configs/ubuntu16_04_clang/9.0.0/bazel_0.27.0/config/BUILD
  configs/ubuntu16_04_clang/9.0.0/bazel_0.27.0/java/BUILD
  configs/ubuntu16_04_clang/versions.bzl
  tests/rbe_repo/BUILD
Labels: approved, lgtm, release, size/XXL

#581 fix 0.26.0 test bazelrc file
  tests/rbe_repo/bazelrc/.bazelrc.0260.notoolchain
Labels: approved, lgtm, size/XS

#583 fix generation of versions.bzl
  configs/ubuntu16_04_clang/versions.bzl
  rules/rbe_repo/outputs.bzl
Labels: approved, lgtm, size/XS

#585 fix test that builds Bazel on RBE
  tests/rbe_external_project/bazel.yaml
Labels: approved, lgtm, size/XS

#587 Add more RBE tests (sanitizers)
  bazelrc/.bazelrc.notoolchain
  tests/rbe_external_project/BUILD.ptrace_platform
  tests/rbe_external_project/abseil_asan.yaml
  tests/rbe_external_project/abseil_msan.yaml
  tests/rbe_external_project/abseil_tsan.yaml
  tests/rbe_external_project/add_asan_platform.sh
  tests/rbe_external_project/bazel_jdk11.yaml
  tests/rbe_external_project/rbe_autoconf_default_targets.txt
  tests/rbe_external_project/rbe_autoconf_default_targets_no_rbe_default.txt
  tests/rbe_repo/bazel_legacy_configs.yaml
Labels: approved, lgtm, size/L

#588 Add small java sample to all RBE tests
  cloudbuild.yaml
  tests/rbe_repo/bazel_incompatible_0_25.yaml
  tests/rbe_repo/bazel_legacy_configs.yaml
  tests/rbe_repo/bazel_legacy_rbe_default.yaml
  tests/rbe_repo/bazel_tests_generate_confs.yaml
  tests/rbe_repo/checked_in_confs.yaml
  tests/rbe_repo/examples/bazel_toolchains_client/WORKSPACE
  tests/rbe_repo/examples/rbe_custom.yaml
  tests/rbe_repo/examples/rbe_custom_base_container_digest.yaml
  tests/rbe_repo/examples/rbe_custom_bazel_versions.yaml
  tests/rbe_repo/examples/rbe_custom_containers.yaml
  tests/rbe_repo/examples/rbe_custom_env.yaml
  tests/rbe_repo/examples/rbe_custom_generate_env.yaml
  tests/rbe_repo/examples/rbe_custom_tag_latest.yaml
  tests/rbe_repo/examples/rbe_custom_toolchain_config_spec_name.yaml
  tests/rbe_repo/examples/rbe_default_jdk11.yaml
  tests/rbe_repo/generate_confs.yaml
  tests/rbe_repo/output_base.yaml
Labels: approved, lgtm, size/L

#590 add test for ubsan
  tests/rbe_external_project/abseil_ubsan.yaml
Labels: approved, lgtm, size/M

#596 fix abseil tests
  tests/rbe_external_project/abseil.yaml
  tests/rbe_external_project/abseil_asan.yaml
  tests/rbe_external_project/abseil_msan.yaml
  tests/rbe_external_project/abseil_tsan.yaml
  tests/rbe_external_project/abseil_ubsan.yaml
Labels: approved, lgtm, size/S

#598 Move more go dependencies to dedicated go deps macro
  WORKSPACE
  repositories/go_repositories.bzl
Labels: approved, lgtm, size/XS

#599 use Bazelisk in rbe_autoconfig
  .bazelci/presubmit.yml
  WORKSPACE
  rules/rbe_repo.bzl
  rules/rbe_repo/container.bzl
  tests/rbe_external_project/abseil_tsan.yaml
  tests/rbe_repo/BUILD
  tests/rbe_repo/bazelisk.sh
Labels: approved, lgtm, size/L

#602 exclude abseil random tests in sanitizer builds
  tests/rbe_external_project/abseil_asan.yaml
  tests/rbe_external_project/abseil_msan.yaml
  tests/rbe_external_project/abseil_tsan.yaml
  tests/rbe_external_project/abseil_ubsan.yaml
Labels: approved, lgtm, size/XS

#603 fix bazel RBE test
  tests/rbe_external_project/bazel.yaml
  tests/rbe_external_project/bazel_bazelisk_rc.yaml
  tests/rbe_external_project/bazel_jdk11.yaml
Labels: approved, lgtm, size/M
